# Generated by Django 6.1.1 on 2026-09-23 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('total_preguntas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('momento', models.CharField(choices=[('pre', 'Pre-evaluación'), ('post', 'Post-evaluación')], max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
