# Generated by Django 6.1.1 on 2026-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoleccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoleccion',
            name='cantidad_residuos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='fecha_recoleccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recoleccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En proceso'), ('recolectada', 'Recolectada'), ('trasladada', 'Trasladada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
