# Generated by Django 6.1.1 on 2026-09-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_estado_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='distrito',
            field=models.CharField(default='Villa El Salvador', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, verbose_name='DNI'),
        ),
    ]
