# Generated by Django 6.1.1 on 2026-09-23 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('peligroso', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('tipo_aparato', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('peso_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='raee/')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ASIGNADO_A_PUNTO', 'Asignado a punto'), ('RECIBIDO_EN_PUNTO', 'Recibido en punto'), ('PENDIENTE_RECOLECCION', 'Pendiente de recolección'), ('EN_RECOLECCION', 'En recolección'), ('RECOLECTADO', 'Recolectado'), ('TRASLADADO', 'Trasladado'), ('TRATADO', 'Tratado / finalizado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raees', to='registro.categoriaraee')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='capacidad_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('capacidad_media', 'Capacidad media'), ('casi_lleno', 'Casi lleno'), ('lleno', 'Lleno'), ('cerrado', 'Temporalmente cerrado'), ('inactivo', 'Inactivo')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='puntoacopio',
            name='capacidad_max',
            field=models.DecimalField(decimal_places=2, help_text='kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='puntoacopio',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='puntoacopio',
            name='operador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_acopio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroraee',
            name='punto_acopio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raees', to='registro.puntoacopio'),
        ),
        migrations.AddField(
            model_name='registroraee',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'rol': 'ciudadano'}, on_delete=django.db.models.deletion.PROTECT, related_name='raees_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
