# Generated by Django 6.1.1 on 2026-09-23 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_categoriaraee_registroraee_delete_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('informacion', 'Información'), ('advertencia', 'Advertencia'), ('critica', 'Crítica')], default='informacion', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('punto_acopio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='registro.puntoacopio')),
                ('raee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='registro.registroraee')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('raee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='registro.registroraee')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_raee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
